# Generated by Django 5.2.1 on 2025-06-27 19:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(help_text='Chave única da configuração', max_length=100, unique=True)),
                ('valor', models.TextField(help_text='Valor da configuração')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do que esta configuração faz')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'db_table': 'whatsapp_configuracoes',
                'ordering': ['chave'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Número do WhatsApp com código do país', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Formato: +5511999999999 ou 5511999999999', regex='^\\+?55\\d{10,11}$')])),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_pessoa', models.CharField(choices=[('fisica', 'Pessoa Física'), ('juridica', 'Pessoa Jurídica')], default='fisica', max_length=10)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18)),
                ('perguntas_realizadas', models.PositiveIntegerField(default=0)),
                ('limite_perguntas', models.PositiveIntegerField(default=3)),
                ('plano_atual', models.CharField(choices=[('novo', 'Novo (3 perguntas)'), ('basico', 'Básico (10 perguntas)'), ('premium', 'Premium (Ilimitado)')], default='novo', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('termos_aceitos', models.BooleanField(default=False)),
                ('termos_aceitos_em', models.DateTimeField(blank=True, null=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('email_verificado_em', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('primeira_pergunta', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, help_text='Vinculação com conta do site MultiBPO', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário WhatsApp',
                'verbose_name_plural': 'Usuários WhatsApp',
                'db_table': 'whatsapp_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(help_text='Pergunta do usuário')),
                ('resposta', models.TextField(help_text='Resposta da IA')),
                ('tokens_utilizados', models.PositiveIntegerField(default=0)),
                ('tempo_processamento', models.FloatField(default=0.0, help_text='Tempo em segundos')),
                ('modelo_ia', models.CharField(default='gpt-4', max_length=50)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('processada_com_sucesso', models.BooleanField(default=True)),
                ('erro_detalhes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='whatsapp_users.whatsappuser')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'db_table': 'whatsapp_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappuser',
            index=models.Index(fields=['phone_number'], name='whatsapp_us_phone_n_042a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappuser',
            index=models.Index(fields=['plano_atual'], name='whatsapp_us_plano_a_350936_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappuser',
            index=models.Index(fields=['created_at'], name='whatsapp_us_created_86a08c_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['whatsapp_user', '-created_at'], name='whatsapp_me_whatsap_05c421_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['created_at'], name='whatsapp_me_created_f7fc48_idx'),
        ),
    ]
