# Generated by Django 5.2.1 on 2025-07-01 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token de Verificação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificado em')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Está Verificado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Cadastro')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_token', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Token de Verificação de Email',
                'verbose_name_plural': 'Tokens de Verificação de Email',
                'db_table': 'whatsapp_email_verification_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
