# Generated by Django 5.2.1 on 2025-07-07 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_users', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaAsaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(help_text='ID do customer no Asaas', max_length=100, verbose_name='Customer ID')),
                ('subscription_id', models.CharField(help_text='ID da subscription no Asaas', max_length=100, unique=True, verbose_name='Subscription ID')),
                ('checkout_url', models.URLField(help_text='URL do checkout gerada pelo Asaas', verbose_name='URL do Checkout')),
                ('valor', models.DecimalField(decimal_places=2, default=29.9, help_text='Valor da assinatura mensal', max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativa'), ('SUSPENDED', 'Suspensa'), ('CANCELLED', 'Cancelada'), ('OVERDUE', 'Em atraso')], default='PENDING', max_length=50, verbose_name='Status')),
                ('origem', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('site', 'Site Web')], default='whatsapp', help_text='Origem da assinatura', max_length=20, verbose_name='Origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('external_reference', models.CharField(blank=True, help_text='Referência externa para o Asaas', max_length=100, verbose_name='Referência Externa')),
                ('next_due_date', models.DateField(blank=True, help_text='Próxima data de cobrança', null=True, verbose_name='Próxima Cobrança')),
                ('whatsapp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='whatsapp_users.whatsappuser', verbose_name='Usuário WhatsApp')),
            ],
            options={
                'verbose_name': 'Assinatura Asaas',
                'verbose_name_plural': 'Assinaturas Asaas',
                'db_table': 'whatsapp_assinatura_asaas',
                'ordering': ['-created_at'],
            },
        ),
    ]
