# Generated by Django 5.2.1 on 2025-06-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritorio',
            name='crc_responsavel',
            field=models.CharField(help_text='CRC do responsável técnico', max_length=20, verbose_name='CRC do Responsável'),
        ),
    ]
