# Generated by Django 5.2.1 on 2025-06-04 19:45

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contadores', '0002_alter_escritorio_crc_responsavel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contador',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Cliente/Contador', 'verbose_name_plural': 'Clientes/Contadores'},
        ),
        migrations.AlterModelOptions(
            name='especialidade',
            options={'ordering': ['area_principal', 'nome'], 'verbose_name': 'Especialidade Contábil (DEPRECATED)', 'verbose_name_plural': 'Especialidades Contábeis (DEPRECATED)'},
        ),
        migrations.AddField(
            model_name='contador',
            name='dados_receita_federal',
            field=models.JSONField(blank=True, default=dict, help_text='Dados da empresa via CNPJ (se pessoa jurídica)', verbose_name='Dados Receita Federal'),
        ),
        migrations.AddField(
            model_name='contador',
            name='documento',
            field=models.CharField(blank=True, help_text='CPF (pessoa física) ou CNPJ (pessoa jurídica)', max_length=18, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='contador',
            name='servicos_contratados',
            field=models.JSONField(blank=True, default=list, help_text='Lista de serviços BPO ativos para este cliente', verbose_name='Serviços BPO Contratados'),
        ),
        migrations.AddField(
            model_name='contador',
            name='tipo_pessoa',
            field=models.CharField(choices=[('fisica', 'Pessoa Física'), ('juridica', 'Pessoa Jurídica')], default='fisica', help_text='Pessoa Física (CPF) ou Jurídica (CNPJ)', max_length=20, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AddField(
            model_name='escritorio',
            name='criado_automaticamente',
            field=models.BooleanField(default=False, help_text='Escritório criado via consulta CNPJ na Receita Federal', verbose_name='Criado Automaticamente'),
        ),
        migrations.AddField(
            model_name='escritorio',
            name='dados_receita_federal',
            field=models.JSONField(blank=True, default=dict, help_text='Dados completos retornados pela API da Receita Federal', verbose_name='Dados Receita Federal'),
        ),
        migrations.AddField(
            model_name='escritorio',
            name='situacao_cadastral',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('inapta', 'Inapta'), ('baixada', 'Baixada'), ('nula', 'Nula')], default='ativa', help_text='Situação na Receita Federal', max_length=20, verbose_name='Situação Cadastral'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Cliente/contador ativo no sistema', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='cargo',
            field=models.CharField(choices=[('proprietario', 'Proprietário/Sócio'), ('diretor', 'Diretor'), ('gerente', 'Gerente'), ('contador_senior', 'Contador Sênior'), ('contador_pleno', 'Contador Pleno'), ('contador_junior', 'Contador Júnior'), ('analista_contabil', 'Analista Contábil'), ('auxiliar_contabil', 'Auxiliar Contábil'), ('estagiario', 'Estagiário'), ('cliente_bpo', 'Cliente BPO'), ('outros', 'Outros')], default='contador_pleno', max_length=100, verbose_name='Cargo/Função'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='categoria_crc',
            field=models.CharField(blank=True, choices=[('contador', 'Contador'), ('tecnico', 'Técnico em Contabilidade')], default='contador', max_length=20, verbose_name='Categoria CRC'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='cpf',
            field=models.CharField(blank=True, help_text="Use campo 'documento' para novos registros", max_length=14, null=True, verbose_name='CPF (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='crc',
            field=models.CharField(blank=True, help_text='Registro no CRC (apenas para contadores profissionais)', max_length=20, null=True, verbose_name='Registro CRC'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='crc_estado',
            field=models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator(message='Estado deve ter 2 letras maiúsculas', regex='^[A-Z]{2}$')], verbose_name='Estado do CRC'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='data_admissao',
            field=models.DateField(blank=True, help_text='Data de entrada no escritório ou cadastro BPO', null=True, verbose_name='Data de Admissão/Cadastro'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='data_demissao',
            field=models.DateField(blank=True, help_text='Data de saída (se aplicável)', null=True, verbose_name='Data de Demissão/Cancelamento'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Data nascimento (PF) ou fundação (PJ)', null=True, verbose_name='Data de Nascimento/Fundação'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='data_registro_crc',
            field=models.DateField(blank=True, help_text='Data de registro no CRC', null=True, verbose_name='Data de Registro CRC'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='email_pessoal',
            field=models.EmailField(blank=True, help_text='E-mail alternativo (além do login)', max_length=254, verbose_name='E-mail Alternativo'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='escritorio',
            field=models.ForeignKey(blank=True, help_text='Escritório onde o contador trabalha', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contadores', to='contadores.escritorio', verbose_name='Escritório'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='especialidades',
            field=models.ManyToManyField(blank=True, help_text="Use campo 'servicos_contratados' para novos registros", related_name='contadores', to='contadores.especialidade', verbose_name='Especialidades (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='formacao',
            field=models.CharField(blank=True, help_text='Curso superior e instituição', max_length=200, verbose_name='Formação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto do perfil (opcional)', null=True, upload_to='contadores/fotos/', verbose_name='Foto do Perfil'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='nome_completo',
            field=models.CharField(help_text='Nome completo (PF) ou razão social (PJ)', max_length=150, verbose_name='Nome Completo/Razão Social'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações internas sobre o cliente/contador', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='telefone_pessoal',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Telefone principal de contato', max_length=128, region='BR', verbose_name='Telefone Principal'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='whatsapp_pessoal',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='WhatsApp para comunicação', max_length=128, region='BR', verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='cep',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato 00000-000', regex='^\\d{5}-?\\d{3}$')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='crc_responsavel',
            field=models.CharField(blank=True, help_text='CRC do responsável técnico', max_length=20, verbose_name='CRC do Responsável'),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail principal do escritório', max_length=254, verbose_name='E-mail Principal'),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='estado',
            field=models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator(message='Estado deve ter 2 letras maiúsculas (ex: SP)', regex='^[A-Z]{2}$')], verbose_name='Estado (UF)'),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='numero',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='responsavel_tecnico',
            field=models.CharField(blank=True, help_text='Nome do contador responsável técnico', max_length=150, verbose_name='Responsável Técnico'),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Telefone principal do escritório', max_length=128, region='BR', verbose_name='Telefone Principal'),
        ),
    ]
